[phases.setup]
nixPkgs = ["go", "nodejs"]

[phases.install]
cmds = ["go mod tidy","cd client && npm install"]

[phases.build]
cmds = [ "go build -o out main.go"]

[start]
cmds = ["go run main.go --server=http && go run main.go --server=websocket && 
       cd client && npm start && ./out"]